/** Display names of the chat vendors the website scan recognizes (API `ChatWidgetProvider` values). */
export const CHAT_WIDGET_PROVIDER_LABELS: Record<string, string> = {
  botpress: 'Botpress',
  brevo: 'Brevo',
  chatbase: 'Chatbase',
  chatra: 'Chatra',
  chatwoot: 'Chatwoot',
  chaport: 'Chaport',
  crisp: 'Crisp',
  drift: 'Drift',
  freshchat: 'Freshchat',
  gorgias: 'Gorgias',
  hubspot: 'HubSpot',
  iadvize: 'iAdvize',
  intercom: 'Intercom',
  ionos: 'IONOS',
  jivochat: 'JivoChat',
  landbot: 'Landbot',
  livechat: 'LiveChat',
  olark: 'Olark',
  smartsupp: 'Smartsupp',
  tawk: 'tawk.to',
  tidio: 'Tidio',
  trengo: 'Trengo',
  userlike: 'Userlike',
  voiceflow: 'Voiceflow',
  zendesk: 'Zendesk',
  zoho_salesiq: 'Zoho SalesIQ',
}
