import type { ProspectionScriptModule } from '~/composables/useProspectionScript'
import type { PresenterVideoModuleWording } from '~/types/PresenterVideoConfig'

/** The words of the clip settings, per module: the site's as they were, the receptionist's in its vocabulary. */
export const PRESENTER_VIDEO_WORDINGS: Record<ProspectionScriptModule, PresenterVideoModuleWording> = {
  websites: {
    title: 'Vos prises pour les sites démo',
    subtitle: '',
    autoGenerateDetail: 'Chaque nouveau site démo génère sa vidéo tout seul, sans action de votre part.',
    flowDetail:
      "Webcam plein écran, puis le site qui défile, puis l'éditeur Storyblok, puis votre appel à l'action. Réglez chaque partie pour coller à votre speech.",
    recordedCutsDetail: 'seule la répartition site / Storyblok se règle.',
    exampleDetail:
      "Chaque prise est montée sur ce site comme un prospect la recevrait. Rien n'est publié, la vraie vidéo du site n'est pas touchée.",
    exampleDemoLabel: "Site d'exemple",
    exampleDemoPlaceholder: 'Choisir un site démo',
    noExampleDemo: 'Aucun site démo actif avec son espace Storyblok : il en faut un pour monter les exemples.',
    resultStepDetail:
      'Son site défile à l’écran, son prénom en incrustation. La vignette cliquable s’ajoute à vos emails via {vignette_video} — ou via l’un des deux modèles « Vidéo » déjà prêts.',
    stayGenericTip: 'ne décrivez jamais une section précise du site.',
    uploadedToast: 'Clip de présentation enregistré — les prochains sites généreront leur vidéo automatiquement',
  },
  'ai-assistant': {
    title: 'Vos prises pour la réceptionniste',
    subtitle:
      'Un discours webcam différent de celui des sites : ici vous présentez la réceptionniste. Il sert d’intro et d’outro à toutes ses vidéos, la démo du chat passe au milieu.',
    autoGenerateDetail: 'Chaque nouvelle réceptionniste génère sa vidéo toute seule, sans action de votre part.',
    flowDetail:
      "Webcam plein écran, puis le chat de la réceptionniste qui répond (un exemple, puis les créneaux), puis son espace client, puis votre appel à l'action.",
    recordedCutsDetail: 'le milieu montre le chat, puis l’espace client.',
    exampleDetail:
      "Chaque prise est montée sur cette réceptionniste comme un prospect la recevrait. Rien n'est publié, sa vraie vidéo n'est pas touchée.",
    exampleDemoLabel: "Réceptionniste d'exemple",
    exampleDemoPlaceholder: 'Choisir une réceptionniste',
    noExampleDemo: 'Aucune réceptionniste active : il en faut une pour monter les exemples.',
    resultStepDetail:
      'Sa réceptionniste répond à l’écran, puis son espace client s’affiche. La vignette cliquable s’ajoute à vos emails via {vignette_video_assistant}, déjà dans les premiers emails « Assistant IA ».',
    stayGenericTip: 'ne citez ni un métier ni le prénom d’une réceptionniste, chaque démo a les siens.',
    uploadedToast:
      'Clip réceptionniste enregistré : les prochaines réceptionnistes généreront leur vidéo automatiquement',
  },
}
