import type { ProspectionScriptModule } from '~/composables/useProspectionScript'

/** How the user can obtain the clip. */
export type PresenterVideoCaptureMode = 'record' | 'import'

export type PresenterVideoConfigProps = {
  module: ProspectionScriptModule
}

/** The words of one module's clip settings; everything else works the same for the site and the receptionist. */
export type PresenterVideoModuleWording = {
  title: string
  subtitle: string
  autoGenerateDetail: string
  flowDetail: string
  recordedCutsDetail: string
  previewDetail: string
  previewPickerLabel: string
  previewPickerPlaceholder: string
  resultStepDetail: string
  stayGenericTip: string
  uploadedToast: string
}

/** A demo the calibration preview can be rendered on: one of the user's sites or receptionists. */
export type PresenterVideoPreviewExample = {
  id: number
  slug: string
  label: string
}

export type PresenterVideoConfigEmits = {
  'has-video': [hasVideo: boolean]
}

/** One part of the video timeline bar (intro, the middle's parts, outro). */
export type PresenterVideoTimelineSegment = {
  key: string
  label: string
  shortLabel: string
  seconds: number
  /** CSS width of the bar segment, proportional to its duration. */
  width: string
  /** Tailwind classes giving the segment its grayscale tone. */
  tone: string
}
