import type { ProspectionScriptModule } from '~/composables/useProspectionScript'
import type { PresenterVideoTake } from '~/types/PresenterVideoTake'

export type PresenterVideoConfigProps = {
  module: ProspectionScriptModule
}

/** The words of one module's clip settings; everything else works the same for the site and the receptionist. */
export type PresenterVideoModuleWording = {
  title: string
  subtitle: string
  autoGenerateDetail: string
  flowDetail: string
  recordedCutsDetail: string
  exampleDetail: string
  exampleDemoLabel: string
  exampleDemoPlaceholder: string
  noExampleDemo: string
  resultStepDetail: string
  stayGenericTip: string
  uploadedToast: string
}

/** A demo the takes' example videos are built on: one of the user's sites or receptionists. */
export type PresenterVideoExampleDemo = {
  id: number
  slug: string
  name: string
}

export type PresenterVideoConfigEmits = {
  'has-video': [hasVideo: boolean]
}

/** A take rendered with cut points not saved yet: it becomes the take's example if exactly these are saved. */
export type PresenterVideoTimingsPreview = {
  take: PresenterVideoTake
  demo: PresenterVideoExampleDemo
  video: Blob
  url: string
}
